import { describe, it, expect } from 'vitest';
import { parseNetscape } from './netscape';
import { toNetscape } from './export';
import type { CookieAttrs } from '../cookie-types';

const HEADER = '# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n';

describe('parseNetscape', () => {
  it('parses a standard seven-field line', () => {
    const { cookies, errors } = parseNetscape(`${HEADER}.example.com\tTRUE\t/\tTRUE\t1893456000\tsession\tabc123\n`);
    expect(errors).toEqual([]);
    expect(cookies).toHaveLength(1);
    expect(cookies[0]).toMatchObject({
      name: 'session',
      value: 'abc123',
      domain: '.example.com',
      path: '/',
      secure: true,
      httpOnly: false,
      hostOnly: false,
      expirationDate: 1893456000,
      sameSite: 'unspecified',
    });
  });

  it('skips comment lines and blank lines', () => {
    const { cookies } = parseNetscape(`# a comment\n\n   \nexample.com\tFALSE\t/\tFALSE\t0\ta\t1\n# trailing comment\n`);
    expect(cookies.map((c) => c.name)).toEqual(['a']);
  });

  it('treats the curl "#HttpOnly_" prefix as an HttpOnly cookie, not a comment', () => {
    const { cookies } = parseNetscape(`#HttpOnly_.example.com\tTRUE\t/\tTRUE\t1893456000\tsid\txyz\n`);
    expect(cookies).toHaveLength(1);
    expect(cookies[0]).toMatchObject({ name: 'sid', domain: '.example.com', httpOnly: true });
  });

  it('marks a cookie host-only when the domain has no leading dot and the flag is FALSE', () => {
    const { cookies } = parseNetscape(`example.com\tFALSE\t/\tFALSE\t0\ta\t1\n`);
    expect(cookies[0]!.hostOnly).toBe(true);
    expect(cookies[0]!.domain).toBe('example.com');
  });

  it('marks a cookie as a domain cookie when the domain has a leading dot', () => {
    const { cookies } = parseNetscape(`.example.com\tTRUE\t/\tFALSE\t0\ta\t1\n`);
    expect(cookies[0]!.hostOnly).toBe(false);
  });

  it('treats an expiry of 0 as a session cookie', () => {
    const { cookies } = parseNetscape(`example.com\tFALSE\t/\tFALSE\t0\ta\t1\n`);
    expect(cookies[0]!.expirationDate).toBeUndefined();
  });

  it('accepts a six-field line as a cookie with an empty value', () => {
    const { cookies, errors } = parseNetscape(`example.com\tFALSE\t/\tFALSE\t0\tflag\n`);
    expect(errors).toEqual([]);
    expect(cookies[0]).toMatchObject({ name: 'flag', value: '' });
  });

  it('reports a malformed line by number and keeps parsing the rest', () => {
    const { cookies, errors } = parseNetscape(`example.com\tFALSE\t/\n.ok.com\tTRUE\t/\tFALSE\t0\tb\t2\n`);
    expect(cookies.map((c) => c.name)).toEqual(['b']);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toMatch(/line 1/i);
  });

  it('reports a non-numeric expiry and skips that line', () => {
    const { cookies, errors } = parseNetscape(`example.com\tFALSE\t/\tFALSE\tsoon\ta\t1\n`);
    expect(cookies).toEqual([]);
    expect(errors[0]).toMatch(/expiry/i);
  });

  it('returns nothing for input that is not Netscape format (no false positives on a header string)', () => {
    const { cookies } = parseNetscape('sid=abc; theme=dark');
    expect(cookies).toEqual([]);
  });

  it('returns nothing for JSON input', () => {
    const { cookies } = parseNetscape('[{"name":"a","value":"1","domain":"e.com"}]');
    expect(cookies).toEqual([]);
  });

  it('round-trips through toNetscape for everything the export format carries', () => {
    // toNetscape does not emit the #HttpOnly_ marker, so httpOnly is the one field that cannot
    // survive a round trip; keep it false here and cover the marker separately above.
    const input: CookieAttrs[] = [
      { name: 'a', value: '1', domain: '.example.com', path: '/', secure: true, httpOnly: false, sameSite: 'lax', hostOnly: false, expirationDate: 1893456000 },
      { name: 'b', value: 'two words', domain: 'example.com', path: '/app', secure: false, httpOnly: false, sameSite: 'unspecified', hostOnly: true },
    ];
    const { cookies, errors } = parseNetscape(toNetscape(input));
    expect(errors).toEqual([]);
    expect(cookies.map(({ name, value, domain, path, secure, hostOnly, expirationDate }) => ({ name, value, domain, path, secure, hostOnly, expirationDate }))).toEqual([
      { name: 'a', value: '1', domain: '.example.com', path: '/', secure: true, hostOnly: false, expirationDate: 1893456000 },
      { name: 'b', value: 'two words', domain: 'example.com', path: '/app', secure: false, hostOnly: true, expirationDate: undefined },
    ]);
  });
});
